version: "3.3"

services:
  notifyer_middleware:
    build: 
      context: notifyer-middleware
    container_name: notifyer-middleware
    hostname: notifyer-middleware
    entrypoint: ["/bin/bash", "./runner.sh"]
    ports:
      - "3000:3000"
    depends_on:
      - db
  notifyer_wpp_server:
    build:
      context: notifyer-wpp-server
    container_name: notifyer-wpp-server
    hostname: notifyer-wpp-server
    volumes:
      - ./notifyer-wpp-server/config.ts:/usr/src/wpp-server/src/config.ts
      - ./wppconnect_tokens:/usr/src/wpp-server/tokens
    ports:
      - "21465:21465"
  db:
    build:
      context: postgres
    container_name: db_postgresql
    hostname: db_postgresql
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  wppconnect_tokens: {}
  postgres-data: {}
