version: "3"

services:
  wppconnect:
    build:
      context: .
    volumes:
      - ./config.ts:/usr/src/notifyerconnect-server/config.ts
      - ./notifyerconnect_tokens:/usr/src/notifyerconnect-server/tokens
    ports:
      - "21465:21465"

volumes:
  notifyerconnect_tokens: {}      